import {
  Instagram,
  Youtube,
  Twitter,
  Facebook,
  Linkedin,
  Twitch,
  Globe,
  DollarSign,
  Camera,
  MessageCircle,
  Play,
  Gamepad2,
} from "lucide-react"

export const socialPlatforms = [
  {
    id: "instagram",
    name: "Instagram",
    icon: Instagram,
    color: "#E4405F",
    placeholder: "@yourhandle",
  },
  {
    id: "youtube",
    name: "YouTube",
    icon: Youtube,
    color: "#FF0000",
    placeholder: "Your Channel",
  },
  {
    id: "tiktok",
    name: "TikTok",
    icon: Play,
    color: "#000000",
    placeholder: "@yourhandle",
  },
  {
    id: "x",
    name: "X",
    icon: Twitter,
    color: "#1DA1F2",
    placeholder: "@yourhandle",
  },
  {
    id: "twitch",
    name: "Twitch",
    icon: Twitch,
    color: "#9146FF",
    placeholder: "yourhandle",
  },
  {
    id: "trovo",
    name: "Trovo",
    icon: Gamepad2,
    color: "#00D4AA",
    placeholder: "yourhandle",
  },
  {
    id: "kick",
    name: "Kick",
    icon: Play,
    color: "#53FC18",
    placeholder: "yourhandle",
  },
  {
    id: "paypal",
    name: "PayPal",
    icon: DollarSign,
    color: "#00457C",
    placeholder: "Support Me",
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    icon: Linkedin,
    color: "#0077B5",
    placeholder: "Connect with me",
  },
  {
    id: "website",
    name: "Website",
    icon: Globe,
    color: "#6366f1",
    placeholder: "Visit my site",
  },
  {
    id: "facebook",
    name: "Facebook",
    icon: Facebook,
    color: "#1877F2",
    placeholder: "Follow me",
  },
  {
    id: "snapchat",
    name: "Snapchat",
    icon: Camera,
    color: "#FFFC00",
    placeholder: "@yourhandle",
  },
  {
    id: "bluesky",
    name: "Bluesky",
    icon: MessageCircle,
    color: "#00A8E8",
    placeholder: "@yourhandle",
  },
]

export const metricTypes = [
  { id: "followers", label: "Total Following", placeholder: "100K+" },
  { id: "reach", label: "Total Reach", placeholder: "1M+" },
  { id: "impressions", label: "Total Impressions", placeholder: "5M+" },
  { id: "engagement", label: "Engagement Rate", placeholder: "8.5%" },
]
